# 참조 : https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#data-properties
spring:
  data:
    cassandra:
      contact-points: localhost
      # username: username
      # password: password
      port: 9042
      schema-action: none
      keyspace-name: hotdeals
      pool:
        max-queue-size: 256
        pool-timeout: 5000ms