apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hotdeals-event-management-deployment
  labels:
    app: hotdeals-event-management
spec:
  selector:
    matchLabels:
      app: hotdeals-event-management
  replicas: 1
  template:
    metadata:
      labels:
        app: hotdeals-event-management
    spec:
      containers:
      - name: hotdeals-event-management
        image: docker.io/ktdatagarage/hotdeals-event-management:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: spring-8080
