spring:
  redis:
    #host: localhost
    jedis:
      pool:
        min-idle: 1
        max-idle: 8
        max-active: 8
    password: "qwer1234"
    sentinel:
      master: mymaster
      nodes: 10.211.55.4:26379

---
# 개발 배포
spring:
  profiles: dev

---
# 상용 배포
spring:
  profiles: prod
