apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: hot-deals
spec:
  replicas: 1
  minReadySeconds: 20
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5
        imagePullPolicy: Always # IfNotPresent
        resources:
          requests:
            cpu: 100m
        ports:
        - name: redis-port
          containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-vol