apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  accessModes:
  #- ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  # nfs로 설정하면 디렉토리를 미리 생성해야한다.
  nfs:
     server: 169.56.115.149
     path: /data/nfs/redis/data