apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-vol
  namespace: hot-deals
spec:
  accessModes:
  #- ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: redis-pv
  volumeMode: Filesystem